#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM microsoft/dotnet:2.1-aspnetcore-runtime-nanoserver-1709 AS base
WORKDIR /app
EXPOSE 61518
EXPOSE 44321

FROM microsoft/dotnet:2.1-sdk-nanoserver-1709 AS build
WORKDIR /src
COPY ["UI/WebClient/WebClient.csproj", "UI/WebClient/"]
RUN dotnet restore "UI/WebClient/WebClient.csproj"
COPY . .
WORKDIR "/src/UI/WebClient"
RUN dotnet build "WebClient.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "WebClient.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "WebClient.dll"]